openapi: 3.0.0
info:
  title: myIoT
  version: '1.0'
  description: ''
  contact: {}
  license:
    name: MasterIT technologies a.s.
servers:
  - url: 'https://develop.masterit.cz'
    description: develop
paths:
  /api/customer/email/exist:
    get:
      summary: CheckLogin
      operationId: get-api-customer-email-exist
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIResult'
              examples:
                OK - email existuje:
                  value:
                    status: ok
                    err_msg: ''
                    err_code: 0
                    data: true
                OK - email neexistuje:
                  value:
                    status: ok
                    err_msg: ''
                    err_code: 0
                    data: false
      description: Metoda zkontroluje existenci emailu pro danou aplikaci
      tags:
        - authorization
      parameters:
        - schema:
            type: string
          in: query
          name: email
          description: email u kterého zjišťujeme existenci
          required: true
        - schema:
            type: string
            example: myIoT
          in: query
          name: app
          description: 'aplikace pro kterou, zjištujeme existenci emailu'
          required: true
    parameters: []
  /api/login:
    post:
      summary: PostLogin
      operationId: post-api-login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIResult'
              examples:
                OK:
                  value:
                    status: ok
                    err_msg: ''
                    err_code: 0
                    data:
                      access_token: token
                      token_type: bearer
                      expires_in: 604800
                      user:
                        note: ''
                        type: scc
                        birth: null
                        email: email@gmail.com
                        recID: 999
                        sccID: 1
                        config:
                          rights:
                            role: user
                            appList: []
                            appRole: []
                            groupID: _default
                            cityList: []
                            groupList: []
                            deviceList: []
                        gender: null
                        mobile: ''
                        userID: 93
                        lastName: Test
                        appUserID: -1
                        firstName: Test
                        userGroup: masterit
                        profession: null
                        sendInvoice: null
                        transportID: null
                        userType: 0
                        tokenID: xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx
                        userLogin: loginTest
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIResult'
              examples:
                Chybné vstupní parametry:
                  value:
                    status: error
                    err_msg: Chybné vstupní parametry
                    err_code: -2000
                    data: null
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIResult'
              examples:
                Uživatel nenalezen:
                  value:
                    status: error
                    err_msg: Uživatel nebyl nalezen
                    err_code: -3001
                    data: null
                Nesprávné heslo:
                  value:
                    status: error
                    err_msg: Uživatelské heslo není správné
                    err_code: -3002
                    data: null
                Uživatelský účet není ověřený:
                  value:
                    status: error
                    err_msg: Uživatelský účet není ověřený
                    err_code: -3003
                    data: null
      description: Provede přihlášení do SCC a získání tokenu
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  description: 'typ přihlášení (scc, email, google, facebook)'
                  example: email
                password:
                  type: string
                  description: uživatelské heslo u facebooku a google nevyžadováno
                login:
                  type: string
                  description: login uživatele (v případě google a fb se zde posílá token)
                app:
                  type: string
                  description: aplikace ze které se přihlašuji
                  example: myIoT
              required:
                - type
                - password
                - login
                - app
            examples:
              SCC:
                value:
                  type: scc
                  login: loginTest
                  password: xxxxxxxxx
              Email:
                value:
                  type: email
                  login: email@gmail.com
                  password: xxxxxxxxxxx
                  app: myIoT
              Google:
                value:
                  login: longGoogle token
                  type: google
              facebook:
                value:
                  login: longFB token
                  type: facebook
        description: ''
      tags:
        - authorization
      parameters:
        - schema:
            type: string
            default: application/json
          in: header
          name: Content-Type
          required: true
components:
  schemas:
    APIResult:
      title: APIResult
      type: object
      properties:
        status:
          type: string
        err_msg:
          type: string
        err_code:
          type: integer
        data:
          type:
            - 'null'
            - object
      x-examples:
        OK:
          status: ok
          err_msg: ''
          err_code: 0
          data: null
        ERROR:
          status: error
          err_msg: Nedostatečné oprávnění
          err_code: -4000
          data: null
  securitySchemes:
    Bearer token:
      type: http
      scheme: bearer
